apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: x-image
  newName: juanjoss/x
  newTag: latest
- name: x-image:juanjoss/x
  newTag: 9b4bb94438ff3f38de0ff6e2e1ca7872529e9ab6
