apiVersion: v1
kind: Service
metadata:
  labels:
    app: x
  name: x
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: x
  name: x
spec:
  selector:
    matchLabels:
      app: x
  template:
    metadata:
      labels:
        app: x
    spec:
      containers:
      - image: ghcr.io/juanjoss/x:e5266ddebe92fc46f43355e9f462ede1728b6a55
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
          targetPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: x
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: x
