name: CD

on: workflow_dispatch

jobs:
  provisioning:
    name: Provision infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform -chdir=terraform/ init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
      - name: Terraform validate
        run: terraform -chdir=terraform/ validate

      - name: Terraform plan
        run: terraform -chdir=terraform/ plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform -chdir=terraform/ apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
