name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  provisioning:
    name: Provision infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform format
        run: terraform -chdir=terraform/ fmt -check >> $GITHUB_STATE

      - name: Terraform plan
        run: terraform -chdir=terraform/ plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform -chdir=terraform/ apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
